server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quesong?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: admin
hello:
  world: dev
logging:
  file: my.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %msg%n)"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %msg%n"
  level:
    root: info